fix(graphql): similar directive sdls on multiple fields fail
nestjs/graphql pull request #2559
Opened 2022-12-16 12:28 UTC by harm-less

Similar directive sdls on multiple fields fail if applied to the same target

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

## What is the current behavior?
I ran into a problem in which the following code doesn't not register all applied directives:

```ts
@Resolver(() => TypeSomething)
export class TwoResolversWithSimilarDirectives {

	@Query((returns) => TypeSomething)
	@Directive('@hasPermission(permissions: APP_ACCOUNTS_READ)')
	@Directive('@limit')
	async retailerAccount() {
		return {}
	}

	@Query((returns) => TypeSomething)
	@Directive('@hasPermission(permissions: APP_RETAILER_ACCOUNTS_READ)')
	@Directive('@limit')
	async retailerAccounts() {
		return []
	}
}
```

As can be seen, I've got 2 resolver methods in 1 target both of which the same SDLs are applied to. Yet, what currently happens is that the second resolver only has one directive applied to the GraphQL schema and not both as intended. 

Issue Number: N/A

## What is the new behavior?
All expected directives are applied to the corresponding fields

## Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

2023-01-02 17:26 UTC, ProKashif requested changes

2023-01-02 17:26 UTC, ProKashif commented on packages/graphql/lib/schema-builder/collections/field-directive.collection.ts
>      }
```suggestion
    if (this.uniqueCombinations.has(combinationKey))   return;
```

2023-02-06 14:08 UTC, kamilmysliwiec commented on packages/graphql/lib/schema-builder/collections/field-directive.collection.ts
> +    if (this.uniqueCombinations.has(combinationKey))   return;
```suggestion
    if (this.uniqueCombinations.has(combinationKey)) { 
        return;
    }
```

2023-02-06 14:08 UTC, kamilmysliwiec commented on packages/graphql/lib/schema-builder/collections/field-directive.collection.ts
> +        return;
```suggestion
      return;
```

2023-02-06 14:08 UTC, kamilmysliwiec commented
LGTM

2023-02-06 14:08 UTC, merged