feat: upgrade Mercurius, Apollo, GraphQL to the latest versions
nestjs/graphql pull request #2636
Opened 2023-02-07 10:42 UTC by kamilmysliwiec

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?
- [x] Yes
- [ ] No

## Other information

2023-02-07 10:50 UTC, kamilmysliwiec commented
@tugascript could you take a look at this test:

![image](https://user-images.githubusercontent.com/23244943/217224829-94f081cc-d19f-41cd-9191-8e700f6dc53e.png)

? (Mercurius hooks related)

2023-02-07 11:32 UTC, tugascript commented
So it seems the gateway hooks no longer exist

2023-02-07 11:43 UTC, tugascript commented
https://github.com/nestjs/graphql/pull/2637

2023-02-07 13:13 UTC, kamilmysliwiec commented
There's only 1 test that is still broken:

![image](https://user-images.githubusercontent.com/23244943/217253942-7c89eebc-6165-4d2c-8647-fb43a23954e3.png)

My hunch is that it's related to this function https://github.com/nestjs/graphql/blob/master/packages/mercurius/lib/utils/build-mercurius-federated-schema.util.ts
cc @Davide-Gheri In the latest version, Mercurius provides its own function for building a schema https://github.com/mercurius-js/mercurius-federation (buildFederationSchema) + another plugin to be used instead of `mercurius` (for federated graphs). Could you take a look & see if there are any adjustments needed @Davide-Gheri (I thought of you as you've implemented the original function in the first place)?

2023-02-08 05:03 UTC, luas10c commented
```ts

// apollo/lib/drivers/apollo-base.driver.ts
...
const apolloPredefinedExceptions: Partial<Record<HttpStatus, string>> = {
  [HttpStatus.BAD_REQUEST]: ApolloServerErrorCode.BAD_USER_INPUT,
  [HttpStatus.UNAUTHORIZED]: 'UNAUTHENTICATED',
  [HttpStatus.FORBIDDEN]: 'FORBIDDEN',
};

...
```
I believe that the predefined errors now come from this enum of the apollo/server/errors package

```ts
// this

import { ApolloServerErrorCode } from '@apollo/server/errors';
```

2023-02-08 07:54 UTC, kamilmysliwiec commented
https://github.com/nestjs/graphql/pull/2636/files#diff-c3a3b52cf11536118537eaffe950a721dd8246bde13d7681c96678d85bec445fR16

As for Forbidden/Unauthorized, Apollo doesn't expose corresponding status codes https://vscode.dev/github.com/apollographql/apollo-server/blob/7d770d4c2fb6d99f8b84eb4dc5c00aaec47e6c99/packages/server/src/errors/index.ts#L3

2023-02-08 12:38 UTC, lpessoa commented
> ```ts
> 
> 
> 
> // apollo/lib/drivers/apollo-base.driver.ts
> 
> ...
> 
> const apolloPredefinedExceptions: Partial<Record<HttpStatus, string>> = {
> 
>   [HttpStatus.BAD_REQUEST]: 'BAD_USER_INPUT',
> 
>   [HttpStatus.UNAUTHORIZED]: 'UNAUTHENTICATED',
> 
>   [HttpStatus.FORBIDDEN]: 'FORBIDDEN',
> 
> };
> 
> 
> 
> ...
> 
> ```
> 
> I believe that the predefined errors now come from this enum of the apollo/server/errors package
> 
> 
> 
> ```ts
> 
> // this
> 
> 
> 
> import { ApolloServerErrorCode } from '@apollo/server/errors';
> 
> ```
> 
> 
Here we followed the error codes and mapped them according to the definitions in https://www.apollographql.com/docs/apollo-server/data/errors#built-in-error-codes.

2023-02-08 13:33 UTC, Davide-Gheri commented
@kamilmysliwiec regarding the Mercurius broken test:
It seems that it is indeed an upstream issue.
That test uses a Query that returns an Union and `@mercurius/gateway` does not support that yet.
I opened an [issue](https://github.com/mercurius-js/mercurius-gateway/issues/59) there, let's see what can be done to fix that

2023-02-08 13:35 UTC, kamilmysliwiec commented
Thank you @Davide-Gheri 🙏

2023-02-14 10:30 UTC, kamilmysliwiec commented
All packages have been published under the `next` tag

2023-02-15 06:37 UTC, juergenzimmermann commented
@kamilmysliwiec please see https://github.com/nestjs/graphql/issues/2655

2023-02-15 12:26 UTC, luas10c commented
The playground is complete and working with cors, following @apollo/server v4 documentation

2023-02-15 15:04 UTC, luas10c commented
@kamilmysliwiec 

You can get the latest changes from this repository check it out and pull it to fix the playground issue

2023-02-16 07:34 UTC, kamilmysliwiec commented
There's no "playground" issue. Current settings are intentional ant this was discussed several times in the past

2023-02-20 07:27 UTC, kamilmysliwiec commented on packages/apollo/lib/drivers/apollo-base.driver.ts
> +    app.use(path, expressMiddleware(server));
Great catch @Davide-Gheri! Would you like to create a PR targeting this PR?

2023-02-28 10:20 UTC, kamilmysliwiec commented on packages/apollo/package.json
> +    "@apollo/server-plugin-landing-page-graphql-playground": "4.0.0",
Move to peer deps

2023-02-28 20:58 UTC, filipefborba commented on packages/apollo/package.json
> +    "@apollo/server-plugin-landing-page-graphql-playground": "4.0.0",
Needing a hand here? I can help!

2023-03-01 11:21 UTC, kamilmysliwiec commented
https://github.com/nestjs/docs.nestjs.com/pull/2640

2023-03-02 16:43 UTC, Tony133 requested changes

2023-03-02 16:43 UTC, Tony133 commented on packages/mercurius/package.json
> +    "mercurius": "12.0.0",
I don't think there are big changes in these small updates, they should solve small problems 😄, however I wanted to point this out before the release of the new version of the `@nestjs/graphql` package🙌

2023-03-08 23:37 UTC, simplenotezy commented
Really cool @kamilmysliwiec - happy to see this, just as I was playing around tonight with upgrading our rather huge application from express to fastify.

What's the proper way to install the 'next' versions exactly? I'd love to test it out, and perhaps provide some feedback, if I should stumble upon anything. I've tried following your additions here: https://github.com/nestjs/docs.nestjs.com/pull/2640/files

I am getting package dependency conflicts. An example repo showing nest 9 running with graphql and fastify would be nice.

2023-03-09 07:16 UTC, kamilmysliwiec commented
@simplenotezy you can use the `--legacy-peer-deps` flag for now (when installing packages)

2023-03-09 13:46 UTC, simplenotezy commented
Thanks @kamilmysliwiec - I'll do that!

2023-03-10 10:09 UTC, merged